// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ChangePictureMAX","status":true,"description":"ピクチャ上限を突破します。ツクールのEditからは101以上のidを指定できないので、helpを参照してください","parameters":{"max_pic_num":"1000"}},
{"name":"PictureAnimation","status":true,"description":"ピクチャのアニメーションプラグイン","parameters":{}},
{"name":"Yami_SkipTitle","status":true,"description":"テストプレイ用にタイトルシーンを飛ばすことができます。","parameters":{}},
{"name":"Game","status":true,"description":"","parameters":{}}
];
